ethereum/emacs-solidity

solidity-mode.el
- Use standard boilerplate and provide Keywords/Copyright/Author
- Add autoload for the mode function
- Remove code which `define-derived-mode` provides implicitly
=> Misc fixes

solidity-mode.el
To support parsing of compiler warnings like:
`hello.sol:1:1: Warning: Source file does not specify required compiler version!Consider adding "pragma solidity ^0.4.13
`
Thanks for this mode! :+1:
=> Flycheck: parse warnings

solidity-mode.el
Fix #15 
The problem was that 
```elisp
(let ((solidity-command (concat solidity-solc-path " " solidity-solc-extra-args)))
(let ((solidity-command (concat solidity-solc-path)))
(setq flycheck-solidity-checker-executable solidity-command)))))
```
would lead to the `flycheck-solidity-checker-executable` having extra args or a trailing space. That worked fine for earlier flycheck versions but in latest flycheck the executable needs to be just the simple path to the executable without any args or even a trailing space.
=> Fix Using Solc and Flycheck for recent Flycheck Versions

README.org, solidity-mode.el
@denisglotov this one is for you
This PR adds integration of Emacs solidity mode and flycheck with the [solium](http://solium.readthedocs.io/en/latest/) linter.
At this point you now need to specify the path to the `solc` or the path to the `solium` binary via 
`solidity-solc-path` or `solidity-solium-path` respectively. Reason is that in some configurations, solc may be added to the path after emacs is launched (e.g. systemd) so it's always good practise to have it explicitly specified.
Moreover since now we can have multiple flycheck checkers you need to specify the active flycheck checker. That is done via the `solidity-flycheck-active-checker` option which can either be `"solc"` or `"solium"`.
Finally check the [README](https://github.com/ethereum/emacs-solidity/blob/master/README.org) …
=> Intergrate with Solium linter

README.org, solidity-mode.el
Read the Readme on how this is possible now.
Note that you need to specifically activate checkers with the following code now.
```emacs-lisp
(setq solidity-flycheck-solc-checker-active t)
(setq solidity-flycheck-solium-checker-active t)
```
Assuming you have properly set the paths too.
=> Chain flycheck checkers

README.org, changelog.MD, solidity-mode.el
You can now get a gas estimate of the function under the cursor, by placing the curson
on top of the function name and typing `C-c C-g`.
You can change this default binding by modifying the keymap in your emacs init file
```emacs-lisp
(define-key map (kbd "C-c C-g") 'solidity-estimate-gas-at-point)
```
=> Gas estimation

README.org, changelog.MD, solidity-mode.el
User can now customize comment style
Default is `/* .. */`
Customize through
```emacs-lisp
(setq solidity-comment-style 'slash)
;; or
(setq solidity-comment-style 'star)
```
=> Option to customize comment style

solidity-mode.el
Highlight `emit` keyword in statements like `emit Event(x);`.
=> Add emit keyword

README.org
Hi, I'm the author of [company-solidity](https://github.com/ssmolkin1/company-solidity), a simple autocompletion back-end for `company-mode`. It's fairly new, but it looks like a number of folks are [already using it](https://melpa.org/#/?q=company-solidity). Together with `solidity-mode`, I think this makes emacs the best text editor for Solidity!  So, I've added a section to the end of the README pointing folks to `company-solidity` for autocompletion.
=> Added autocompletion section to readme

README.org, changelog.MD, company-solidity.el, solidity-mode.el
As discussed, [here](https://github.com/ethereum/emacs-solidity/pull/25), I've fully integrated [company-solidity](https://github.com/ssmolkin1/company-solidity) into `solidity-mode`. Similar to what is done for the `solidity-flycheck`, `company-solidity` will automatically be required by `solidity-mode` if `company-mode` is installed.
The list of autocompletion targets is now pulled from the `solidity-mode` keywords lists for syntax highlighting, as well as a number of additional keywords that aren't present there. I had a good look through the official documentation as I prepared this, so hopefully the list is complete (for now).
Some of these additional keywords should probably be syntax-highlighted as well, so should be copied over to the relevant `solidity-mode` keyword lists (at …
=> Integrated company-solidity for autocompletion

README.org, changelog.MD, solidity-flycheck.el
- By default value of `solidity-solc-path` is "solc", therefore
`(file-executable-p solidity-solium-path)` always return `nil`
unless `solidity-solium-path` is set to absolute path. This is fixed
by replace `file-executable-p` with `flycheck-executable-find`.
- The flycheck checkers configurations codes are not loaded when
`(require solidity-mode)`, moved them to a function to explicitly
call in config.
=> fixes flycheck integration

solidity-flycheck.el
=> Remove no longer existing --use-std solc option

solidity-flycheck.el
I have labeled this "WIP" for now because it is presently only a "works for me" patch for working with my version of solium (1.1.8), and I am sure there needs to be some version-handling added to make this still handle output from older versions too, rather than only the newer one. When I find time I will try to add version-handling backward-compatibility, but that might take a while, so please add a commit of your own to do that if you don't want to wait.
Aside from updating the parsing for the new output format, I also needed to add the reporter flag because the default output reporter is now "pretty".
=> Conditionally add flag to solium invocation & tweak output parsing for newer solium

README.org
Using `map` causes an error. Using `solidity-mode-map` fixes it for me.
=> Suggest actual mode map name: solidity-mode-map

changelog.MD, solidity-mode.el
According to Issue #42.
I am quite new to Elisp and Lisp in general, so further corrections are welcomed! :smile:
=> Added support for Imenu

solidity-mode.el
e.g, when "struct" occurs in "constructor", don't color "struct".
This is achieved by adding word boundaries in regexps, inside the solidity-match-* functions.
=> Avoid keyword-coloring keywords when they're substrings of tokens

solidity-mode.el
#49.
It is hard for me to switch `c-mode` with `prog-mode`.
This is workaround to avoid running `c-mode-hook` in solidity-mode.
=> Avoid running c-mode-hook.

solidity-flycheck.el, solidity-mode.el
This patch makes it so that the solidity flycheck checker works
properly with solc versions >= 0.6.0
Since the output of solc >= 0.6.0 differs quite a bit from the old
versions we then utilize the `--old-reporter` argument which reverts
to the previous form of output.
=> Adjust package for solc >= 0.6.0. Also bump version to v0.1.10

solidity-mode.el
This ensures that if the two optional matches in the regexp, `\\[ *[0-9]*\\]` or
`(regexp-opt solidity-variable-modifier 'words)` have no match, the name of the
variable being declared can be still be found via the absolute match index 2.
Prior to this change, a simple `address foo` would match the regexp, but the
expected match index for the variable, 4, would have no match, which could lead
to font-lock errors in some circumstances.
[Reference for shy matches](
https://www.gnu.org/software/emacs/manual/html_node/emacs/Regexp-Backslash.html#index-shy-group_002c-in-regexp-1000)
Fixes #47
=> Make solidity-match-variable-decls regexp's unhighlited matches shy.

solidity-mode.el
Something to think about: should "let" be under `soliidty-keywords` or `solidity-builtin-types`?
Currently, opted for the latter because I want it to be highlighted similar to `int x = 1`;
=> Add keyword let

solidity-mode.el
Currently  `solidity-mode` sets `c-basic-offset` to 2 by default.
[Solidity Style Guide](https://solidity.readthedocs.io/en/v0.6.8/style-guide.html#indentation) says to use 4 spaces per indentation level.
=> Set c-basic-offset to 4

solidity-flycheck.el
In 0.8.0, the --old-reporter flag was removed. This caused solidity-flycheck to error
out. We add error patterns for the new reporter format and use the new format for
solidity >= 0.6.0, when it was first introduced.
Closes https://github.com/ethereum/emacs-solidity/issues/62
=> Fix solidity-flycheck for solidity >= 0.8.0

.gitignore, solidity-flycheck.el, solidity-mode.el, test/solidity-flycheck-tests.el, test/solidity-mode-test-setup.el
solidity-flycheck can now detect projects.
When `solidity-flycheck-use-project` is t, solidity-flycheck will detect a project
and include files in the project during compilation and linting. solidity-flycheck
will look for a .soliumrc.json in a parent directory. If found, this directory is
considered the project root. If no .soliumrc.json is found, `project-roots` is used.
When `solidity-flycheck-solium-checker-active` is t, the .soliumrc.json found in
the project root will be used as the solium config, rather than a .soliumrc.json
in the same directory as the file being linted.
When `solidity-flycheck-solc-checker-active` is t, the project root will be passed
to solc using the --allow-paths flag. This means imports to other files inside the
project will lint without erorr.
The custom …
=> solidity-flycheck: Support project root and additional allow-paths

solidity-flycheck.el
Only include a solc remapping if it references a path that actually exists. 
This is an enhancement from my previous PR. The motivation: I was using a global allow-path that was present on one of my machines but not the other, causing checking to fail. IMO It seems reasonable to only include remappings for paths that actually exist.
=> Ignore solc remappings that don't exist

solidity-mode.el
The overlapping range [A-z] includes non-identifier characters: "[^`".
=> Fix invalid identifier regex (overlapping range)

solidity-mode.el
A feature from Solidity 0.8.8. (will likely release next week.)
Syntax looks like: `type MyAddress is address;`
=> Added support for highlighting user defined value types.

solidity-mode.el
Hi,
I created a quick PR to fix the indentation of the close parenthesis in function calls.
Here is what the current indentation looks like:
```solidity
require(
store == msg.sender || owner() == msg.sender,
"caller is neither store nor owner"
);            // This parenthesis looks unaligned
```
This PR will push the close parenthesis to align with the function call:
```solidity
require(
cccStore == msg.sender || owner() == msg.sender,
"caller is neither cccStore nor owner"
);                   // Now it's aligned 
```
Can you take a look and merge if it's useful?
Thanks!
=> fix indentation for the close parenthesis of function calls

solidity-common.el, solidity-flycheck.el
Hi again. I made this branch a while ago when I started on a project that uses solhint. I added solhint support and also reworked the flycheck checker initialization. 
The main reason I wanted to rework flycheck checker initialization is that flycheck has its own logic to enable or disable checkers based on the presence of the `:command` binary, and also handles locally installed linters with its `flycheck-some-checker-executable` variables. So we can simplify this package's configuration by always defining the checker, and letting flycheck handle enabling/disabling it. 
The second reason is basically https://github.com/ethereum/emacs-solidity/issues/41. I'd expect to be able to require the package and set variables it defines after it is loaded. The changes in this PR mean I don't need …
=> Simplify checkers and add solhint

solidity-mode.el
Hi,
This PR updates the syntax table so that `$` is also a part of a word (according to Solidity's grammar: https://docs.soliditylang.org/en/v0.8.16/grammar.html#a4.SolidityLexer.Identifier)
Can you review and consider merging it?
Thanks!
=> update syntax to accept the dollar sign as part of a word
